---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/certstrap --version
    register: certstrap_test_output
  - name: certstrap --version
    debug:
      msg: '{{ certstrap_test_output.stdout }}'
